name: Vienna Li
title: Vienna Li
email: viennnali@gmail.com
description: Hi! Vienna here. I am a graphic + digital designer passionate about building delightful experiences.
# baseurl: "/portfolio"
url: ""
twitter_username: viennnali
github_username: viennnali
